CREATE TABLE MEMBER
(
  NAME VARCHAR2(20 BYTE) NOT NULL
, EMAIL VARCHAR2(100 BYTE) NOT NULL
, PASSWORD VARCHAR2(20 BYTE) NOT NULL
, STUDENT_NUMBER NUMBER NOT NULL
, GRADE NUMBER NOT NULL
, MAJOR VARCHAR2(50 BYTE) NOT NULL
, PROFILE_IMAGE VARCHAR2(300 BYTE)
);

CREATE TABLE CATEGORY
(
  FOODTYPE VARCHAR2(20 BYTE) NOT NULL
);

CREATE TABLE POST
(
  TITLE VARCHAR2(20 BYTE) NOT NULL
, DESC VARCHAR2(900 BYTE) NOT NULL
, PHOTO VARCHAR2(300 BYTE)
, USERNAME VARCHAR2(100 BYTE) NOT NULL
, CATEGORY VARCHAR2(100 BYTE) NOT NULL
);